# Generated by Django 5.1.4 on 2024-12-23 23:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'get_latest_by': 'date_joined', 'ordering': ['-date_joined']},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
