# Generated by Django 5.1.4 on 2024-12-24 17:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lookupvalue',
            name='core_lookup_categor_6727b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='lookupvalue',
            name='core_lookup_categor_f4f61d_idx',
        ),
        migrations.RemoveField(
            model_name='lookupvalue',
            name='color',
        ),
        migrations.RemoveField(
            model_name='lookupvalue',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='lookupvalue',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='lookupvalue',
            name='is_system',
        ),
        migrations.AlterField(
            model_name='lookupcategory',
            name='code',
            field=models.CharField(help_text='Unique code for the lookup category', max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='lookupcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the lookup category', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='lookupcategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lookupcategory',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Whether this is a system-defined category', verbose_name='System Category'),
        ),
        migrations.AlterField(
            model_name='lookupcategory',
            name='name',
            field=models.CharField(help_text='Name of the lookup category', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='lookupvalue',
            name='category',
            field=models.ForeignKey(help_text='The category this value belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='values', to='core.lookupcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='lookupvalue',
            name='code',
            field=models.CharField(help_text='Unique code within the category', max_length=50, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='lookupvalue',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of what this value represents', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='lookupvalue',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lookupvalue',
            name='name',
            field=models.CharField(help_text='Display name for this value', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='lookupvalue',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional parent value for hierarchical lookups', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.lookupvalue', verbose_name='Parent Value'),
        ),
        migrations.AlterField(
            model_name='lookupvalue',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which to display this value', verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
