# Generated by Django 5.1.4 on 2024-12-24 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_add_initial_lookup_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Join Date'),
        ),
    ]
