# Generated by Django 5.1.4 on 2024-12-24 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_projectmember_join_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when this object was created', verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Date and time when this object was last updated', verbose_name='Updated Date')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this object is active. Inactive objects are treated as deleted.', verbose_name='Active')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this object', verbose_name='Notes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data stored as JSON', verbose_name='Metadata')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('created_by', models.ForeignKey(help_text='User who created this object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(help_text='User who last updated this object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
    ]
